# Generated by Django 5.1.4 on 2024-12-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogo",
            name="arte_jogo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
