# Generated by Django 5.1.4 on 2024-12-09 17:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0002_jogo_arte_jogo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jogo",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
