# Generated by Django 5.1.4 on 2024-12-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0004_rename_jogo_presenca_jogo_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="presenca",
            old_name="jogo_id",
            new_name="jogo",
        ),
    ]
