# Generated by Django 5.1.4 on 2024-12-09 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0005_rename_jogo_id_presenca_jogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='presenca',
            constraint=models.UniqueConstraint(fields=('usuario', 'jogo'), name='unique_usuario_jogo'),
        ),
    ]
