# Generated by Django 5.1.4 on 2024-12-11 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0009_desempenhojogador_presenca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desempenhojogador",
            name="presenca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="desempenhos",
                to="jogos.presenca",
            ),
        ),
    ]
