# Generated by Django 5.1.4 on 2024-12-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0002_alter_jogador_assistencias_alter_jogador_clean_sheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
