# Generated by Django 5.1.4 on 2024-12-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_newuser_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='assets/media'),
        ),
    ]
