# Generated by Django 5.1.4 on 2024-12-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_newuser_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
