# Generated by Django 5.1.4 on 2024-12-09 17:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_alter_newuser_foto_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newuser",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
